version: 2

jobs:
  deploy:
    machine: true
    steps:
      - run:
          name: Deploy latest code using SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /opt/near/rainbow-bridge && git pull && make bsc-testnet-update && make bsc-testnet-start-relayer && make bsc-testnet-status"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: bsc-testnet
