FROM node:16.8.0-alpine3.11
WORKDIR /opt/web

RUN apk --no-cache add git nodejs yarn

COPY ./ ./

## init
RUN yarn && yarn install

## gen-contracts
RUN cd /opt/web/contracts/eth/nearbridge/ && yarn && yarn build && \
    cd /opt/web/contracts/eth/nearprover/ && yarn && yarn build

## init-config
RUN mkdir -p ${HOME}/.rainbow && \
    cp /opt/web/config.json ${HOME}/.rainbow/config.json