# Add  environment file named .env placed in the project directory.
version: '3.7'
services:
  eth2near-relay:
    build:
      context: ../../
      dockerfile: ./.docker.bsc/testnet/Dockerfile.bsc-deploy
    image: near:latest
    container_name: eth2near-relay
    restart: always
    command: cli/index.js start eth2near-relay --gas-per-transaction 100000000000000 --total-submit-block 3 --daemon false

  near2eth-relay:
    image: near:latest
    container_name: near2eth-relay
    restart: always
    command: cli/index.js start near2eth-relay --daemon false


  bridge-watchdog:
    image: near:latest
    container_name: bridge-watchdog
    restart: always
    command: cli/index.js start bridge-watchdog --daemon false
    depends_on:
      - eth2near-relay
      - near2eth-relay